server:
  port: 8081

multiplication:
  exchange: multiplication_exchange
  solved:
    key: multiplication.solved
  queue: multiplication_queue
  anything:
    routing-key: 'multiplication.*'
  service-id: multiplication # used for feign

multiplicationHost: http://localhost:8080/api #using feign instead
swagger:
  enable: true

spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: 'jdbc:h2:file:~/gamification;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE'
  rabbitmq:
    host: localhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/